app/about/__init__.py
from flask import Blueprint

about = Blueprint('about', __name__)

from . import routes

app/about/routes.py
from flask import render_template
from . import about


@about.route("/")
def index():
    return render_template("views/about.html")

app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import routes

app/home/routes.py
from flask import render_template
from . import home


@home.route("/")
def index():
    return render_template("views/home.html")

app/record/__init__.py
from flask import Blueprint

record = Blueprint('record', __name__)

from . import routes

app/record/routes.py
import os

from flask import render_template, Response
from controllers.video_controller import video_controller

from . import record


@record.route("/<filename>")
def index(filename):
    return render_template("views/record.html", filename=filename)


@record.route('/video_feed/<filename>')
def video_feed(filename):
    video_path = os.path.join('uploads', 'video', filename)
    video_controller.start(video_path)
    return Response(generate_frames(), mimetype='multipart/x-mixed-replace; boundary=frame')


def generate_frames():
    while True:
        frame = video_controller.get_frame()
        if frame is None:
            video_controller.stop()  # Stop processing when no frames are available
            break
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')

app/stream/__init__.py
from flask import Blueprint

stream = Blueprint('stream', __name__)

from . import routes

app/stream/routes.py
from flask import render_template, Response

from controllers.camera import camera
from . import stream


@stream.route("/")
def index():
    return render_template("views/stream.html")


@stream.route('/start_camera')
def start_camera():
    camera.start()
    return "Camera started"


@stream.route('/stop_camera')
def stop_camera():
    camera.stop()
    return "Camera stopped"


@stream.route('/stream')
def streaming():
    return Response(generate_frame(), mimetype='multipart/x-mixed-replace; boundary=frame')


def generate_frame():
    while True:
        frame = camera.generate_frame_from_model()
        if frame:
            yield (b'--frame\r\n'
                   b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')

app/upload/__init__.py
from flask import Blueprint

upload = Blueprint('upload', __name__)

from . import routes

app/upload/routes.py
import os

from flask import render_template, request, flash, redirect, url_for

from . import upload


@upload.route("/")
def index():
    files = os.listdir('uploads/video')
    return render_template("views/upload.html", files=files)


@upload.route('/upload_video', methods=['POST'])
def upload_video():
    if "file" not in request.files:
        flash("No file part")
        return redirect(request.url)

    file = request.files['file']
    if file.filename == '':
        flash("No selected file")
        return redirect(request.url)

    if file:
        filename = file.filename
        file.save(os.path.join('uploads/video', filename))
        flash('File saved successfully!')
        return redirect(url_for('upload.index'))


@upload.route('/delete/<filename>', methods=['POST'])
def delete(filename):
    video_path = os.path.join('uploads/video', filename)
    os.remove(video_path)
    flash("File deleted successfully!")
    return redirect(url_for('upload.index'))

templates/views/about.html
{% extends "layouts/main_layouts.html" %}

{% block content %}
  <h1 class="bg-red-500">Welcome About!</h1>
  <p>This is the about page content.</p>
{% endblock %}

templates/views/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Violation Detection App</title>
    <link href="{{ url_for('static',filename='css/output.css') }}" rel="stylesheet">
</head>
<body>
<div class="h-screen w-screen flex flex-col justify-center items-center gap-8">
    <h1 class="text-4xl font-black">Helm Violation <br>Detection App</h1>
    <div class="flex gap-4">
        <a href="{{ url_for('stream.index') }}" class="bg-gray-200 p-8 rounded-lg hover:bg-gray-300 shadow cursor-pointer">
            <p>From Camera</p>
        </a>
        <a href="{{ url_for('upload.index') }}" class="bg-gray-200 p-8 rounded-lg hover:bg-gray-300 shadow cursor-pointer">
            <p>From Video</p>
        </a>
    </div>
</div>
</body>
</html>

templates/views/record.html
{% extends "layouts/main_layouts.html" %}

{% block content %}
    <div class="grid grid-cols-9 grid-rows-8 gap-4 h-screen p-4">
        <div class="col-span-6 row-span-6 overflow-hidden rounded-md">
            <h1 class="text-2xl font-bold mb-[10px]">Video Detection</h1>
            <img src="{{ url_for('record.video_feed', filename=filename) }}" class="h-full w-full rounded-md" alt="">
        </div>

        <div class="col-span-3 row-span-8 overflow-hidden rounded-md">
            <h2 class="text-base font-semibold mt-[8px] mb-[10px] text-gray-600">Violation Result</h2>
            <div id="file-list" class="rounded-md bg-gray-200 w-full h-full">
            </div>
        </div>

        <div class="col-span-3 row-span-2 rounded-md bg-gray-200">
            <div></div>
        </div>

        <div class="col-span-3 row-span-2 rounded-md bg-gray-200">
            <div></div>
        </div>
    </div>
{% endblock %}

templates/views/stream.html
{% extends "layouts/main_layouts.html" %}

{% block content %}
    <div class="grid grid-cols-9 grid-rows-8 gap-4 h-screen p-4">
        <div class="col-span-6 row-span-6 overflow-hidden rounded-md">
            <h1 class="text-2xl font-bold mb-[10px]">Realtime Violation Detection</h1>
            <div class="rounded-md bg-gray-200 w-full h-full">
                <div id="videoCover" class="bg-gray-200 h-full rounded-md flex flex-col justify-center items-center w-full">
                    <button class="bg-red-500 py-4 px-8 rounded-md text-white" onclick="startCamera()">Start Camera
                    </button>
                </div>
                <div id="videoFeed" style="display: none" class="bg-gray-200 h-full rounded-md w-full relative group/canvas">
                    <img src="{{ url_for('stream.streaming') }}" class="h-full w-full rounded-md" alt="">
                    <div
                            class="absolute top-0 left-0 group-hover/canvas:opacity-100 flex opacity-0 justify-center items-center w-full h-full transition-all duration-100">
                        <button class="bg-red-500 py-4 px-8 rounded-md text-white" onclick="stopCamera()">
                            Stop Camera
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-span-3 row-span-8 overflow-hidden rounded-md">
            <h2 class="text-base font-semibold mt-[8px] mb-[10px] text-gray-600">Violation Result</h2>
            <div class="rounded-md bg-gray-200 w-full h-full">
            </div>
        </div>

        <div class="col-span-3 row-span-2 rounded-md bg-gray-200">
            <div></div>
        </div>

        <div class="col-span-3 row-span-2 rounded-md bg-gray-200">
            <div></div>
        </div>
    </div>

    <script>
        function startCamera() {
            fetch('/stream/start_camera')
                .then(response => {
                    if (response.ok) {
                        document.getElementById('videoFeed').style.display = 'block';
                        document.getElementById('videoCover').classList.add("hidden");
                    }
                });
        }

        function stopCamera() {
            fetch('/stream/stop_camera')
                .then(response => {
                    if (response.ok) {
                        document.getElementById('videoFeed').style.display = 'none';
                        document.getElementById('videoCover').classList.remove("hidden");
                    }
                });
        }
    </script>
{% endblock %}

templates/views/upload.html
{% extends "layouts/main_layouts.html" %}

{% block content %}
    <div class="grid grid-cols-5 gap-4 h-screen p-4">
        <div class="col-span-3 h-full w-full overflow-hidden flex flex-col">
            <h1 class="text-2xl font-bold mb-[10px]">Uploaded Video List</h1>
            <ul class="gap-2 flex flex-col overflow-y-scroll h-full">
                {% if files %}
                    {% for file in files %}
                        <li class="bg-gray-200 w-full p-4 rounded-md hover:bg-gray-300 flex justify-between items-center">
                            {{ file }}
                            <form id="delete-form-{{ file }}" action="{{ url_for('upload.delete', filename=file) }}"
                                  method="POST" style="display: none;">
                            </form>
                            <div class="flex justify-between items-center gap-2">
                                <button onclick="window.location='{{ url_for('record.index', filename=file) }}'"
                                        class="bg-indigo-500 hover:bg-indigo-600 px-4 py-2 rounded-md text-white text-sm">
                                    Detect Video
                                </button>
                                <button onclick="if(confirm('Are you sure delete this file?')){document.getElementById('delete-form-{{ file }}').submit()};"
                                        class="bg-red-500 hover:bg-red-600 px-4 py-2 rounded-md text-white text-sm">
                                    {% include 'components/remove_icon.html' %}
                                </button>
                            </div>
                        </li>
                    {% endfor %}
                {% else %}
                    <li class="bg-gray-200 w-full p-4 rounded-md flex justify-between items-center">
                        No File, Please upload file first!
                    </li>
                {% endif %}
            </ul>
        </div>
        <div class="col-span-2 overflow-hidden rounded-md">
            <h2 class="text-base font-semibold mt-[8px] mb-[10px] text-gray-600">Upload Video</h2>
            <div class="w-full h-full">
                <form id="uploadForm" action="{{ url_for('upload.upload_video') }}" method="POST"
                      enctype="multipart/form-data">
                    <input type="file" name="file" id="fileInput" required class="">
                    <button type="submit">Upload</button>
                </form>
                <div id="loadingIndicator" style="display: none;">Uploading...</div>
                <script src="{{ url_for('static', filename='js/upload.js') }}"></script>
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        <ul>
                            {% for message in messages %}
                                <li>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                {% endwith %}
            </div>
        </div>
    </div>
{% endblock %}